/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbemiLekeTicTacToe;

/**
 *
 * @author ajiboyeaGbemileke
 */
public class mainMenu extends javax.swing.JFrame {
        Player player1=new Player();
        Player player2= new Player();

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        //this was added because of the error face by the player1 name collection field
        p1TxtField.setVisible(false);
        p2TxtField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        mainMenuPan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        twoPlayerInfoPan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p1TxtField = new javax.swing.JTextField();
        p2TxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gamePlayPan = new javax.swing.JPanel();
        player1NameLabel = new javax.swing.JLabel();
        player2NameLabel = new javax.swing.JLabel();
        player1ScoreLabel = new javax.swing.JLabel();
        player2ScoreLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        point0 = new javax.swing.JLabel();
        point1 = new javax.swing.JLabel();
        point2 = new javax.swing.JLabel();
        point3 = new javax.swing.JLabel();
        point4 = new javax.swing.JLabel();
        point5 = new javax.swing.JLabel();
        point6 = new javax.swing.JLabel();
        point7 = new javax.swing.JLabel();
        point8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nextPlayerLebel = new javax.swing.JLabel();
        blabla = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gbemilekeInfo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        howToPlayPan = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainMenuPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainItem3.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        mainMenuPan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 230, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainItem1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        mainMenuPan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainItem2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        mainMenuPan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainItem4.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        mainMenuPan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenuPs.png"))); // NOI18N
        mainMenuPan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        twoPlayerInfoPan.setMinimumSize(new java.awt.Dimension(404, 460));
        twoPlayerInfoPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/startgame.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        twoPlayerInfoPan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backBtn.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        twoPlayerInfoPan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 40));

        p1TxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p1TxtField.setForeground(new java.awt.Color(255, 0, 51));
        p1TxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1TxtField.setBorder(null);
        p1TxtField.setOpaque(false);
        p1TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1TxtFieldActionPerformed(evt);
            }
        });
        twoPlayerInfoPan.add(p1TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, 20));

        p2TxtField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p2TxtField.setForeground(new java.awt.Color(255, 0, 51));
        p2TxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2TxtField.setBorder(null);
        p2TxtField.setOpaque(false);
        twoPlayerInfoPan.add(p2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 220, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/toPlayerInfoBg.png"))); // NOI18N
        twoPlayerInfoPan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gamePlayPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player1NameLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        player1NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        player1NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1NameLabel.setText("Player one name");
        gamePlayPan.add(player1NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 20));

        player2NameLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        player2NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        player2NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2NameLabel.setText("Player two name");
        gamePlayPan.add(player2NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 130, 20));

        player1ScoreLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        player1ScoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        player1ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1ScoreLabel.setText("0");
        gamePlayPan.add(player1ScoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 90, 40));

        player2ScoreLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        player2ScoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        player2ScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2ScoreLabel.setText("0");
        gamePlayPan.add(player2ScoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 90, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/endGamebtn.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        gamePlayPan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, 50));

        point0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point0MouseClicked(evt);
            }
        });
        gamePlayPan.add(point0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        point1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point1MouseClicked(evt);
            }
        });
        gamePlayPan.add(point1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        point2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point2MouseClicked(evt);
            }
        });
        gamePlayPan.add(point2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        point3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point3MouseClicked(evt);
            }
        });
        gamePlayPan.add(point3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        point4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point4MouseClicked(evt);
            }
        });
        gamePlayPan.add(point4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        point5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point5MouseClicked(evt);
            }
        });
        gamePlayPan.add(point5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        point6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point6MouseClicked(evt);
            }
        });
        gamePlayPan.add(point6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        point7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point7MouseClicked(evt);
            }
        });
        gamePlayPan.add(point7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        point8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png"))); // NOI18N
        point8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point8MouseClicked(evt);
            }
        });
        gamePlayPan.add(point8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resetBoard.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        gamePlayPan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        nextPlayerLebel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nextPlayerLebel.setForeground(new java.awt.Color(255, 255, 255));
        nextPlayerLebel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nextPlayerLebel.setText("DEFAULT");
        gamePlayPan.add(nextPlayerLebel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 130, 20));

        blabla.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        blabla.setForeground(new java.awt.Color(0, 0, 255));
        blabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blabla.setText("NEXT PLAYER :");
        gamePlayPan.add(blabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gamePlaybg.png"))); // NOI18N
        gamePlayPan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gbemilekeInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("E-MAIL :");
        gbemilekeInfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("TEL  :");
        gbemilekeInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("about  :");
        gbemilekeInfo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("gbemilekelee@gmail.com");
        gbemilekeInfo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("08080069909, 08166364847");
        gbemilekeInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 190, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ajiboye Gbemileke");
        gbemilekeInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("NAME  :");
        gbemilekeInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("will be available in the next version");
        gbemilekeInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baktoMain.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        gbemilekeInfo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/developerImage copy.png"))); // NOI18N
        gbemilekeInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        howToPlayPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baktoMain.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        howToPlayPan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/howtoplay.png"))); // NOI18N
        howToPlayPan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPan, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(twoPlayerInfoPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(gamePlayPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(gbemilekeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(howToPlayPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(twoPlayerInfoPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(gamePlayPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(gbemilekeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(howToPlayPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(rootPane,"SORRY!!! This mode is available in v2.0 and higher versions only");
        /*jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/toPlayerInfoBg.png")));
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);*/
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        mainMenuPan.setVisible(false);
        p1TxtField.setVisible(true);//same reason as below
        p2TxtField.setVisible(true);//this was asseded because of the error in the text field
        twoPlayerInfoPan.setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void p1TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1TxtFieldActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        twoPlayerInfoPan.setVisible(false);
         mainMenuPan.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
        player1.setName(p1TxtField.getText());
        player2.setName(p2TxtField.getText());
        nextPlayerLebel.setText(player1.getName());
        player1NameLabel.setText(player1.getName());
        player2NameLabel.setText(player2.getName());
        twoPlayerInfoPan.setVisible(false);
        gamePlayPan.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void point0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point0MouseClicked
        // TODO add your handling code here:
        if(Player.currentPlayer==1) point0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
        Player.updateWhowins(Player.currentPlayer,0);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
   
    }//GEN-LAST:event_point0MouseClicked

    private void point1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point1MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,1);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point1MouseClicked

    private void point2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point2MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,2);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
        
    }//GEN-LAST:event_point2MouseClicked

    private void point3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point3MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,3);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point3MouseClicked

    private void point4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point4MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,4);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point4MouseClicked

    private void point5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point5MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,5);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point5MouseClicked

    private void point6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point6MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,6);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point6MouseClicked

    private void point7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point7MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,7);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point7MouseClicked

    private void point8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point8MouseClicked
        // TODO add your handling code here:
         if(Player.currentPlayer==1) point8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xPea.png")));
        else point8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oPea.png")));
          Player.updateWhowins(Player.currentPlayer,8);
        if(Player.checkWhoWins()==1){
        player1.setScore(player1.getScore()+1);
        player1ScoreLabel.setText(Integer.toString(player1.getScore()));
        }
        else if(Player.checkWhoWins()==2){
        player2.setScore(player2.getScore()+1);
        player2ScoreLabel.setText(Integer.toString(player2.getScore()));
        }
        Player.UpdateCurrentPlayer();
        if(Player.currentPlayer==1) nextPlayerLebel.setText(player1.getName());
        else nextPlayerLebel.setText(player2.getName());
    }//GEN-LAST:event_point8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
       for(int i=0;i<9;i++) Player.whoWines[i]=0;
      point0.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point2.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point3.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point4.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point5.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point6.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point7.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point8.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
       
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here
        if(Integer.parseInt(player1ScoreLabel.getText())>Integer.parseInt(player2ScoreLabel.getText()))
                javax.swing.JOptionPane.showMessageDialog(rootPane,player1.getName()+" WON THE GAME");
       else if(Integer.parseInt(player1ScoreLabel.getText())<Integer.parseInt(player2ScoreLabel.getText()))
               javax.swing.JOptionPane.showMessageDialog(rootPane,player2.getName()+" WON THE GAME");
       else javax.swing.JOptionPane.showMessageDialog(rootPane," IT'S A DRAW");
        
        gamePlayPan.setVisible(false);
        p1TxtField.setText(null);
        p2TxtField.setText(null);
        player1.setScore(0);
        player2.setScore(0);
        player1ScoreLabel.setText("0");
        player2ScoreLabel.setText("0");
      point0.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point1.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point2.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point3.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point4.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point5.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point6.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point7.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
      point8.setIcon( new javax.swing.ImageIcon(getClass().getResource("/images/defaultPea.png")));
        mainMenuPan.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:        
          gbemilekeInfo.setVisible(true);
          twoPlayerInfoPan.setVisible(false);
          gamePlayPan.setVisible(false);
          mainMenuPan.setVisible(false);
          
          
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        gbemilekeInfo.setVisible(false);
          mainMenuPan.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        howToPlayPan.setVisible(false);
          mainMenuPan.setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        howToPlayPan.setVisible(true);
         gbemilekeInfo.setVisible(false);
          twoPlayerInfoPan.setVisible(false);
          gamePlayPan.setVisible(false);
          mainMenuPan.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blabla;
    private javax.swing.JPanel gamePlayPan;
    private javax.swing.JPanel gbemilekeInfo;
    private javax.swing.JPanel howToPlayPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainMenuPan;
    private javax.swing.JLabel nextPlayerLebel;
    private javax.swing.JTextField p1TxtField;
    private javax.swing.JTextField p2TxtField;
    private javax.swing.JLabel player1NameLabel;
    private javax.swing.JLabel player1ScoreLabel;
    private javax.swing.JLabel player2NameLabel;
    private javax.swing.JLabel player2ScoreLabel;
    private javax.swing.JLabel point0;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point2;
    private javax.swing.JLabel point3;
    private javax.swing.JLabel point4;
    private javax.swing.JLabel point5;
    private javax.swing.JLabel point6;
    private javax.swing.JLabel point7;
    private javax.swing.JLabel point8;
    private javax.swing.JPanel twoPlayerInfoPan;
    // End of variables declaration//GEN-END:variables
}
